name: Publish package to npmjs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com/

      - name: Install PNPM
        run: npm i pnpm -g

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Typescript to Javsacript and add env node line
        run: pnpm build

      - name: Set Git user information
        run: |
          git config user.email "seyadeodin@gmail.com"
          git config user.name "Lucas"

      - name: Increase version number
        run: pnpm version patch

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m ":wrench: chore: Update package.json"

      - name: Publish to npm
        run:  pnpm publish --no-git-checks --tag latest --access=public

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
