name: Publish package to npmjs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install PNPM
        run: npm i pnpm -g

      - name: Install dependencies
        run: ppm ci

      - name: Build Typescript to Javsacript and add env node line
        run: pnpm build

      - name: Increase version number
        run: pnpm version patch

      - name: Publish to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
